name: pnpm
description: 'Setup node & pnpm'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: true
    - uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
